/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import ups.edu.ec.controlador.ControladorInicioSesion;
import ups.edu.ec.controlador.ControladorPersona;
import ups.edu.ec.controlador.ControladorTelefono;

/**
 *
 * @author santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    ControladorPersona controladorPersona;
    ControladorTelefono controladorTelefono;
    VentanaRegistro ventanaRegistro;
    VentanaTelefono ventanTelefono;
    VentanaPersona ventanaPersona;
    ControladorInicioSesion controladorInicioSesion;
    VentanaIniciarSesion ventanaIniciarSesion;
    
    
    public VentanaPrincipal() {
        initComponents();
        
        
        controladorInicioSesion = ControladorInicioSesion.getIntancia();
        ventanaRegistro = new VentanaRegistro(controladorInicioSesion);
        controladorPersona = new ControladorPersona();
        controladorTelefono = new ControladorTelefono();
        ventanTelefono = new VentanaTelefono(controladorTelefono);
        ventanaPersona = new VentanaPersona(controladorPersona);
        ventanaIniciarSesion = new VentanaIniciarSesion(controladorInicioSesion, this);
        
        itemVentaanaPersona.setVisible(false);
        itemVentanaaTelefono.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemVentanaRegistro = new javax.swing.JMenuItem();
        itemIniciarSesion = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        itemMenuGestion = new javax.swing.JMenu();
        itemVentaanaPersona = new javax.swing.JMenuItem();
        itemVentanaaTelefono = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        itemVentanaRegistro.setText("VentanaRegistro");
        itemVentanaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentanaRegistroActionPerformed(evt);
            }
        });
        fileMenu.add(itemVentanaRegistro);

        itemIniciarSesion.setText("Ventana Iniciar Sesion");
        itemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(itemIniciarSesion);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        itemMenuGestion.setText("Gestion");

        itemVentaanaPersona.setText("VentanaPersona");
        itemVentaanaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentaanaPersonaActionPerformed(evt);
            }
        });
        itemMenuGestion.add(itemVentaanaPersona);

        itemVentanaaTelefono.setMnemonic('a');
        itemVentanaaTelefono.setText("VentanaTelefono");
        itemVentanaaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentanaaTelefonoActionPerformed(evt);
            }
        });
        itemMenuGestion.add(itemVentanaaTelefono);

        menuBar.add(itemMenuGestion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void itemVentanaaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentanaaTelefonoActionPerformed
        
        desktopPane.add(ventanTelefono);
        ventanTelefono.setVisible(true);
        

    }//GEN-LAST:event_itemVentanaaTelefonoActionPerformed

    private void itemVentanaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentanaRegistroActionPerformed
        
        desktopPane.add(ventanaRegistro);
        ventanaRegistro.setVisible(true);

    }//GEN-LAST:event_itemVentanaRegistroActionPerformed

    private void itemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionActionPerformed
        
        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);
        

    }//GEN-LAST:event_itemIniciarSesionActionPerformed

    private void itemVentaanaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentaanaPersonaActionPerformed
        
        desktopPane.add(ventanaPersona);
        ventanaPersona.setVisible(true);

    }//GEN-LAST:event_itemVentaanaPersonaActionPerformed
    
    public JMenuItem itemVentanaTelefono() {
        
        return itemVentanaaTelefono;
        
    }
    
    public JMenuItem itemVentanaPersona() {
        
        return itemVentaanaPersona;
        
    }
    
    
    
    
            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemIniciarSesion;
    private javax.swing.JMenu itemMenuGestion;
    private javax.swing.JMenuItem itemVentaanaPersona;
    private javax.swing.JMenuItem itemVentanaRegistro;
    private javax.swing.JMenuItem itemVentanaaTelefono;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
